spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6jk3ma4d50c738vbm9g-a:5432/vibha_db
spring.datasource.username=mantesh_k
spring.datasource.password=Sg5wOafJn1HuZUqFx6j213alHADgwsqE

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.cors.allowed-origins=*
app.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
app.cors.allowed-headers=*

app.security.jwt.secret=mySuperSecretKeyForJwtToken123456789
app.security.jwt.expiration-ms=86400000

app.upload.dir=${APP_UPLOAD_DIR:/tmp/uploads}